namespace Minecraft.Schemas.Entities.Meta;

public enum MetaFieldType {
    Byte = 0,
    VarInt = 1,
    VarLong = 2,
    Float = 3,
    String = 4,
    TextComponent = 5,
    OptionalTextComponent = 6,
    Slot = 7,
    Boolean = 8,
    Rotations = 9,
    Position = 10,
    OptionalPosition = 11,
    Direction = 12,
    OptionalLivingEntityReference = 13,
    BlockState = 14,
    OptionalBlockState = 15,
    Particle = 16,
    Particles = 17,
    VillagerData = 18,
    OptionalVarInt = 19,
    Pose = 20,
    CatVariant = 21,
    CowVariant = 22,
    WolfVariant = 23,
    WolfSoundVariant = 24,
    FrogVariant = 25,
    PigVariant = 26,
    ChickenVariant = 27,
    OptionalGlobalPosition = 28,
    PaintingVariant = 29,
    SnifferState = 30,
    ArmadilloState = 31,
    CopperGolemState = 32,
    WeatheringCopperState = 33,
    Vector3 = 34,
    Quaternion = 35,
    ResolvableProfile = 36
}
